language: python

install:
  - sudo apt-get install ant
  - export PROJECT_ROOT=`pwd`
  - cd $HOME; hg clone http://hg.python.org/jython && hg update v2.7b3 && cd jython && ant;
  - export PATH=$HOME/jython/dist/bin:$PATH;jython --version
  - cd $PROJECT_ROOT

# Before run the test case, we need to make jython run some code
before_script:
  - jython -c "print 'HELLO'"

# test script
script:
  - pwd
  - echo "test"

