language: python

install:
  - sudo apt-get install ant
  - hg clone http://hg.python.org/jython && cd jython && ant;
  - export PATH=$HOME/jython/dist/bin:$PATH;jython --version

# Before run the test case, we need to make jython run some code
before_script:
  - jython -c "print 'HELLO'"

# test script
script:
  - echo "test"

