language: python

install:
  - wget 'http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7-b2/jython-standalone-2.7-b2.jar' -O jython-standalone.jar
  - java -jar jython-standalone.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH;jython --version

# Before run the test case, we need to make jython run some code
before_script:
  - jython -c "print ''"

# test script
script:
  - echo "test"

